"use client";
import { useMemo, useState } from "react";
import { Card, CardHeader, CardBody } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/Badge";
import { Calendar, Video, Users2, ClipboardList } from "lucide-react";
import { AgendaActions } from "@/components/operations/AgendaActions";
type Event={id:string;title:string;type:string;start_at:string;end_at:string|null;responsible_name:string;status:string;related_to:string|null};
const icons:Record<string,React.ElementType>={reuniao:Users2,visita:Calendar,gravacao:Video,tarefa:ClipboardList,compromisso_interno:Calendar};
const labels:Record<string,string>={reuniao:"Reunião",visita:"Visita",gravacao:"Gravação",tarefa:"Tarefa",compromisso_interno:"Compromisso interno"};
type View="Dia"|"Semana"|"Mês";
function startOfWeek(date:Date){const d=new Date(date);const day=d.getDay();const diff=day===0?-6:1-day;d.setDate(d.getDate()+diff);d.setHours(0,0,0,0);return d;}
function endOfWeek(date:Date){const d=startOfWeek(date);d.setDate(d.getDate()+7);return d;}
export function AgendaView({events}:{events:Event[]}){const[view,setView]=useState<View>("Semana");const today=new Date();const filtered=useMemo(()=>events.filter(e=>{const d=new Date(e.start_at);if(view==="Dia")return d.toDateString()===today.toDateString();if(view==="Semana"){const s=startOfWeek(today),end=endOfWeek(today);return d>=s&&d<end;}return d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth();}),[events,view]);const grouped=filtered.reduce<Record<string,Event[]>>((a,e)=>{const key=e.start_at.slice(0,10);(a[key]??=[]).push(e);return a},{});return <div className="space-y-4"><div className="flex gap-1.5 rounded-lg border border-ink-300 bg-white p-1 text-xs w-fit">{(["Dia","Semana","Mês"] as View[]).map(v=><button key={v} type="button" onClick={()=>setView(v)} className={`rounded-md px-3 py-1.5 font-medium ${view===v?"bg-korvix-900 text-white":"text-ink-500"}`}>{v}</button>)}</div>{Object.entries(grouped).map(([day,list])=><Card key={day}><CardHeader title={new Date(day+"T00:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}/><CardBody className="!p-0"><div className="divide-y divide-ink-100">{list.map(e=>{const Icon=icons[e.type]??Calendar;return <div key={e.id} className="flex items-center gap-4 px-5 py-3.5"><div className="w-14 text-xs text-ink-500">{new Date(e.start_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</div><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-korvix-50 text-korvix-600"><Icon size={15}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-ink-900">{e.title}</p><p className="text-xs text-ink-500">{labels[e.type]??e.type} · {e.responsible_name}</p></div><StatusBadge status={e.status}/><AgendaActions id={e.id}/></div>})}</div></CardBody></Card>)}{filtered.length===0&&<Card><CardBody><p className="text-sm text-ink-500">Nenhum evento encontrado nesta visualização.</p></CardBody></Card>}</div>}
