"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Plus, X } from "lucide-react";
export function CreateTaskButton({ userName }: { userName: string }) {
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(fd:FormData){setSaving(true);setError("");const title=String(fd.get("title")||"").trim();if(!title){setError("Informe a tarefa.");setSaving(false);return;}const {error:e}=await createClient().from("tasks").insert({title,assigned_to_name:String(fd.get("assigned_to_name")||userName),priority:String(fd.get("priority")||"media"),status:"pendente",due_date:String(fd.get("due_date")||new Date().toISOString().slice(0,10)),related_entity_type:String(fd.get("related_entity_type")||"cliente"),related_entity_label:String(fd.get("related_entity_label")||"")||null});if(e){setError(e.message);setSaving(false);return;}window.location.reload();}
 return <><button onClick={()=>setOpen(true)} className="focus-ring flex items-center justify-center gap-2 rounded-lg bg-korvix-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-korvix-800"><Plus size={16}/> Nova tarefa</button>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form action={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">Nova tarefa</h3><p className="text-sm text-ink-500">A tarefa será salva no Supabase.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input name="title" required placeholder="Tarefa" className="w-full rounded-lg border p-2.5"/><input name="assigned_to_name" defaultValue={userName} placeholder="Responsável" className="w-full rounded-lg border p-2.5"/><div className="grid grid-cols-2 gap-3"><select name="priority" defaultValue="media" className="rounded-lg border p-2.5"><option value="baixa">baixa</option><option value="media">media</option><option value="alta">alta</option><option value="urgente">urgente</option></select><input name="due_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="rounded-lg border p-2.5"/></div><input name="related_entity_label" placeholder="Vincular a (opcional)" className="w-full rounded-lg border p-2.5"/><select name="related_entity_type" defaultValue="cliente" className="w-full rounded-lg border p-2.5"><option value="cliente">Cliente</option><option value="lead_oportunidade">Oportunidade</option><option value="contrato">Contrato</option><option value="audiovisual">Audiovisual</option><option value="agenda">Agenda</option><option value="usuario">Usuário</option></select>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={saving} className="rounded-lg bg-korvix-900 px-4 py-2 text-white">{saving?"Salvando...":"Criar tarefa"}</button></div></form></div>}</>;
}
