"use client";
import { useState } from "react";
import { Pencil, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Task = { id:string; title:string; assigned_to_id:string|null; priority:string; status:string; due_date:string; related_entity_type:string; related_entity_label:string };
type User = { id:string; name:string };

export function TaskActions({ task, users, isAdmin }: { task:Task; users:User[]; isAdmin:boolean }) {
  const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function remove(){ if(!window.confirm("Excluir esta tarefa?")) return; const {error:e}=await createClient().from("tasks").delete().eq("id",task.id); if(e){setError(e.message);return;} window.location.reload(); }
  async function save(fd:FormData){ setSaving(true);setError(""); const payload={title:String(fd.get("title")||"").trim(),assigned_to_id:String(fd.get("assigned_to_id")||"")||task.assigned_to_id,assigned_to_name:users.find(u=>u.id===String(fd.get("assigned_to_id")))?.name||undefined,priority:String(fd.get("priority")||"media"),status:String(fd.get("status")||"pendente"),due_date:String(fd.get("due_date")||task.due_date),related_entity_type:String(fd.get("related_entity_type")||"cliente"),related_entity_label:String(fd.get("related_entity_label")||"")}; if(!payload.title){setError("Informe a tarefa.");setSaving(false);return;} const {error:e}=await createClient().from("tasks").update(payload).eq("id",task.id); if(e){setError(e.message);setSaving(false);return;} window.location.reload(); }
  return <div className="flex gap-1"><button type="button" onClick={()=>setOpen(true)} className="rounded-md p-1.5 text-ink-500 hover:bg-ink-50" aria-label="Editar tarefa"><Pencil size={14}/></button><button type="button" onClick={remove} className="rounded-md p-1.5 text-red-500 hover:bg-red-50" aria-label="Excluir tarefa"><Trash2 size={14}/></button>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form action={save} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h3 className="text-lg font-semibold">Editar tarefa</h3><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input name="title" defaultValue={task.title} className="w-full rounded-lg border p-2.5" required/><select name="assigned_to_id" defaultValue={task.assigned_to_id||users[0]?.id||""} disabled={!isAdmin} className="w-full rounded-lg border p-2.5">{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><select name="priority" defaultValue={task.priority} className="rounded-lg border p-2.5"><option>baixa</option><option>media</option><option>alta</option><option>urgente</option></select><select name="status" defaultValue={task.status} className="rounded-lg border p-2.5"><option>pendente</option><option>em_andamento</option><option>concluida</option><option>cancelada</option></select></div><input name="due_date" type="date" defaultValue={task.due_date} className="w-full rounded-lg border p-2.5"/><input name="related_entity_label" defaultValue={task.related_entity_label||""} placeholder="Vincular a (opcional)" className="w-full rounded-lg border p-2.5"/><select name="related_entity_type" defaultValue={task.related_entity_type} className="w-full rounded-lg border p-2.5"><option value="cliente">Cliente</option><option value="lead_oportunidade">Oportunidade</option><option value="contrato">Contrato</option><option value="audiovisual">Audiovisual</option><option value="agenda">Agenda</option><option value="usuario">Usuário</option></select>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={saving} className="rounded-lg bg-korvix-900 px-4 py-2 text-white">{saving?"Salvando...":"Salvar"}</button></div></form></div>}</div>;
}
