import { Card, CardHeader, CardBody } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/Badge";
import { Calendar, Video, Users2, ClipboardList } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { CreateAgendaButton } from "@/components/operations/CreateAgendaButton";

type Event={id:string;title:string;type:string;start_at:string;end_at:string|null;responsible_name:string;status:string;related_to:string|null};
const icons:Record<string,React.ElementType>={reuniao:Users2,visita:Calendar,gravacao:Video,tarefa:ClipboardList,compromisso_interno:Calendar};
const labels:Record<string,string>={reuniao:"Reunião",visita:"Visita",gravacao:"Gravação",tarefa:"Tarefa",compromisso_interno:"Compromisso interno"};
export default async function AgendaPage(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const[{data:events,error},{data:profile}]=await Promise.all([supabase.from("agenda_events").select("id,title,type,start_at,end_at,responsible_name,status,related_to").order("start_at",{ascending:true}),supabase.from("users").select("name").eq("id",user.id).maybeSingle()]);if(error)return <div className="rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-700">Não foi possível carregar a agenda: {error.message}</div>;const rows=(events??[]) as Event[];const grouped=rows.reduce<Record<string,Event[]>>((a,e)=>{const d=e.start_at.slice(0,10);(a[d]??=[]).push(e);return a},{});return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold tracking-tight text-ink-900">Agenda</h2><p className="text-sm text-ink-500">Visão unificada de compromissos.</p></div><CreateAgendaButton userName={profile?.name??user.email??"Usuário"}/></div><div className="flex gap-1.5 rounded-lg border border-ink-300 bg-white p-1 text-xs w-fit">{["Dia","Semana","Mês"].map((v,i)=><button key={v} className={`rounded-md px-3 py-1.5 font-medium ${i===1?"bg-korvix-900 text-white":"text-ink-500"}`}>{v}</button>)}</div>{Object.entries(grouped).map(([day,list])=><Card key={day}><CardHeader title={new Date(day+"T00:00:00").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}/><CardBody className="!p-0"><div className="divide-y divide-ink-100">{list.map(e=>{const Icon=icons[e.type]??Calendar;return <div key={e.id} className="flex items-center gap-4 px-5 py-3.5"><div className="w-14 text-xs text-ink-500">{new Date(e.start_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</div><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-korvix-50 text-korvix-600"><Icon size={15}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-ink-900">{e.title}</p><p className="text-xs text-ink-500">{labels[e.type]??e.type} · {e.responsible_name}</p></div><StatusBadge status={e.status}/></div>})}</div></CardBody></Card>)}{rows.length===0&&<Card><CardBody><p className="text-sm text-ink-500">Nenhum evento cadastrado. Use Novo evento para começar.</p></CardBody></Card>}</div>}
