import { Card, CardHeader, CardBody } from "@/components/ui/Card";
import { StatCard } from "@/components/ui/StatCard";
import { StatusBadge } from "@/components/ui/Badge";
import { TrendingUp, Wallet, Users, ClipboardList, Target } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default async function DashboardPage(){
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return null;
 const [o,c,p,cm,ct,t,av,g]=await Promise.all([s.from("opportunities").select("id,client_name,stage,estimated_value,probability").order("created_at",{ascending:false}),s.from("clients").select("id,operational_status"),s.from("payments").select("amount,status"),s.from("commissions").select("amount"),s.from("contracts").select("value,frequency,status"),s.from("tasks").select("id,status,due_date"),s.from("av_demands").select("id,status"),s.from("goals").select("id,vendor_name,metric,target,achieved").order("created_at",{ascending:false})]);
 const opp=o.data??[],clients=c.data??[],payments=p.data??[],commissions=cm.data??[],contracts=ct.data??[],tasks=t.data??[],av=av.data??[],goals=g.data??[];
 const won=opp.filter(x=>x.stage==="ganho"||x.stage==="fechado_ganho"); const open=opp.filter(x=>!['ganho','perdido','fechado_ganho','fechado_perdido'].includes(x.stage)); const paid=payments.filter(x=>x.status==="pago").reduce((a,x)=>a+Number(x.amount||0),0); const com=commissions.reduce((a,x)=>a+Number(x.amount||0),0); const overdue=payments.filter(x=>x.status==="atrasado").reduce((a,x)=>a+Number(x.amount||0),0); const mrr=contracts.filter(x=>x.status==="ativo").reduce((a,x)=>a+(x.frequency==="mensal"?Number(x.value||0):Number(x.value||0)/12),0);
 return <div className="space-y-6"><div><h2 className="text-xl font-semibold tracking-tight text-ink-900">Korvix Command Center</h2><p className="text-sm text-ink-500">Dados operacionais em tempo real do Supabase.</p></div>
 <section><div className="mb-3 flex items-center gap-2"><TrendingUp size={15}/><h3 className="text-sm font-semibold">Comercial</h3></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Oportunidades abertas" value={String(open.length)} icon={Target}/><StatCard label="Vendas fechadas" value={String(won.length)}/><StatCard label="Conversão" value={`${opp.length?Math.round(won.length/opp.length*100):0}%`}/><StatCard label="Pipeline" value={money(open.reduce((a,x)=>a+Number(x.estimated_value||0),0))}/></div></section>
 <section><div className="mb-3 flex items-center gap-2"><Wallet size={15}/><h3 className="text-sm font-semibold">Financeiro</h3></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Faturamento pago" value={money(paid)}/><StatCard label="Receita líquida" value={money(paid-com)}/><StatCard label="MRR" value={money(mrr)}/><StatCard label="Inadimplência" value={money(overdue)}/></div></section>
 <div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><Card><CardHeader title="Clientes"/><CardBody className="space-y-3"><Mini label="Operação" v={clients.filter(x=>x.operational_status==="operacao").length}/><Mini label="Onboarding" v={clients.filter(x=>x.operational_status==="onboarding").length}/><Mini label="Renovação" v={clients.filter(x=>x.operational_status==="renovacao").length}/></CardBody></Card><Card><CardHeader icon={<ClipboardList size={16}/>} title="Operação"/><CardBody className="space-y-3"><Mini label="Tarefas abertas" v={tasks.filter(x=>x.status!=="concluida").length}/><Mini label="Tarefas atrasadas" v={tasks.filter(x=>x.status!=="concluida"&&new Date(x.due_date)<new Date()).length}/><Mini label="Audiovisual pendente" v={av.filter(x=>!['PUBLISHED','CANCELLED','FINALIZED'].includes(x.status)).length}/></CardBody></Card><Card><CardHeader icon={<Users size={16}/>} title="Equipe"/><CardBody className="space-y-4">{goals.slice(0,5).map(x=><div key={x.id}><div className="flex justify-between text-xs"><span>{x.vendor_name} · {x.metric}</span><span>{x.achieved}/{x.target}</span></div><div className="mt-1 h-1.5 rounded bg-ink-100"><div className="h-full rounded bg-korvix-500" style={{width:`${Math.min(100,Number(x.target)?Number(x.achieved)/Number(x.target)*100:0)}%`}}/></div></div>)}</CardBody></Card></div>
 <Card><CardHeader title="Últimas oportunidades"/><CardBody className="!p-0"><div className="divide-y divide-ink-100">{opp.slice(0,10).map(x=><div key={x.id} className="flex items-center justify-between px-5 py-3.5"><div><p className="font-medium">{x.client_name}</p><p className="text-xs text-ink-500">{money(Number(x.estimated_value||0))}</p></div><StatusBadge status={x.stage}/></div>)}</div>{opp.length===0&&<p className="p-5 text-sm text-ink-500">Nenhuma oportunidade ainda. Vá ao CRM e crie a primeira.</p>}</CardBody></Card></div>;
}
function Mini({label,v}:{label:string;v:number}){return <div className="flex justify-between"><span className="text-sm text-ink-700">{label}</span><span className="text-lg font-semibold">{v}</span></div>}
